/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "id": "pb_59pj54cwk2o7xty",
    "name": "Graphs",
    "type": "base",
    "system": false,
    "listRule": "@request.auth.id != \"\" && (owner = @request.auth.id || visibility != \"private\")",
    "viewRule": "@request.auth.id != \"\" && (owner = @request.auth.id || visibility != \"private\")",
    "createRule": "@request.auth.id != \"\" && owner = @request.auth.id",
    "updateRule": "@request.auth.id != \"\" && owner = @request.auth.id",
    "deleteRule": "@request.auth.id != \"\" && owner = @request.auth.id",
    "fields": [
    {
      "name": "id",
      "id": "text3208210256",
      "type": "text",
      "required": true,
      "autogeneratePattern": "[a-z0-9]{15}",
      "hidden": false,
      "max": 15,
      "min": 15,
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "system": true,
    },
    {
      "name": "owner",
      "id": "relationeqf7slqfvw",
      "type": "relation",
      "required": true,
      "collectionId": "_pb_users_auth_",
      "maxSelect": 1,
      "minSelect": 0,
      "cascadeDelete": true,
    },
    {
      "name": "uid",
      "id": "textxd2xouxelx",
      "type": "text",
      "required": true,
      "min": 1,
      "max": 64,
      "pattern": "^[A-Za-z0-9_-]{1,64}$",
    },
    {
      "name": "name",
      "id": "textwtltyd0sur",
      "type": "text",
      "required": true,
      "min": 1,
      "max": 100,
      "pattern": "^[a-z0-9_]+$",
    },
    {
      "name": "label",
      "id": "text0wuqbuulp5",
      "type": "text",
      "required": true,
      "min": 1,
      "max": 200,
    },
    {
      "name": "namespace",
      "id": "textdr1hk8o12c",
      "type": "text",
      "required": false,
      "max": 32,
      "pattern": "^[a-z0-9]{1,32}$",
    },
    {
      "name": "description",
      "id": "textvedot3ox0p",
      "type": "text",
      "required": false,
      "max": 2000,
    },
    {
      "name": "visibility",
      "id": "selectrl9cdqt03m",
      "type": "select",
      "required": true,
      "maxSelect": 1,
      "values": ["private", "unlisted", "public"],
    },
    {
      "name": "tags",
      "id": "jsonh6l33re3kx",
      "type": "json",
      "required": false,
    },
    {
      "name": "created",
      "id": "autodate2990389176",
      "type": "autodate",
      "required": false,
      "hidden": false,
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": true,
    },
    {
      "name": "updated",
      "id": "autodate3332085495",
      "type": "autodate",
      "required": false,
      "hidden": false,
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": true,
    },
  ],
    "indexes": [
    "CREATE UNIQUE INDEX `idx_graphs_owner_namespace_uid` ON `Graphs` (`owner`, `namespace`, `uid`)",
    "CREATE INDEX `idx_graphs_owner` ON `Graphs` (`owner`)",
    "CREATE INDEX `idx_graphs_visibility` ON `Graphs` (`visibility`)",
  ],
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pb_59pj54cwk2o7xty") // Graphs;
  return app.delete(collection);
});
